<?php

/**
 * BasetkArea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $pos
 * @property Doctrine_Collection $tkTask
 * 
 * @method string              getName()   Returns the current record's "name" value
 * @method integer             getPos()    Returns the current record's "pos" value
 * @method Doctrine_Collection getTkTask() Returns the current record's "tkTask" collection
 * @method tkArea              setName()   Sets the current record's "name" value
 * @method tkArea              setPos()    Sets the current record's "pos" value
 * @method tkArea              setTkTask() Sets the current record's "tkTask" collection
 * 
 * @package    tigerkanban
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetkArea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tk_area');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('pos', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('tkTask', array(
             'local' => 'id',
             'foreign' => 'area_id'));
    }
}