<?php

/**
 * BasetkTask
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $link
 * @property integer $area_id
 * @property integer $sf_guard_user_id
 * @property float $effort
 * @property tkArea $area
 * @property sfGuardUser $user
 * 
 * @method string      getTitle()            Returns the current record's "title" value
 * @method string      getLink()             Returns the current record's "link" value
 * @method integer     getAreaId()           Returns the current record's "area_id" value
 * @method integer     getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method float       getEffort()           Returns the current record's "effort" value
 * @method tkArea      getArea()             Returns the current record's "area" value
 * @method sfGuardUser getUser()             Returns the current record's "user" value
 * @method tkTask      setTitle()            Sets the current record's "title" value
 * @method tkTask      setLink()             Sets the current record's "link" value
 * @method tkTask      setAreaId()           Sets the current record's "area_id" value
 * @method tkTask      setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method tkTask      setEffort()           Sets the current record's "effort" value
 * @method tkTask      setArea()             Sets the current record's "area" value
 * @method tkTask      setUser()             Sets the current record's "user" value
 * 
 * @package    tigerkanban
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetkTask extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tk_task');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('area_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sf_guard_user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('effort', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('tkArea as area', array(
             'local' => 'area_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as user', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id'));
    }
}