<?php

/**
 * tkAreaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tkAreaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tkAreaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tkArea');
    }
}