<?php

/**
 * tkLaneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tkLaneTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tkLaneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tkLane');
    }
}