tkLane:
  actAs:
    Timestampable: ~
  columns:
    name: string(255)
    pos: integer
    sf_guard_group_id: integer(4);
  relations:
    team:
      class: sfGuardGroup
      local: sf_guard_group_id
      foreign: id
      type: one

tkArea:
  actAs:
    Timestampable: ~
  columns:
    name: string(255)
    pos: integer
    sf_guard_group_id: integer(4),
    wip: integer
    area_type: integer
  relations:
    team:
      class: sfGuardGroup
      local: sf_guard_group_id
      foreign: id
      type: one

tkTask:
  actAs:
    NestedSet:
      hasManyRoots: true
      rootColumnName: root_id
    Timestampable: ~
  columns:
    title: string(255)
    link: string(255)
    area_id: integer
    lane_id: integer
    creator_id: integer(4)
    sf_guard_user_id: integer(4)
    effort: float
    finished: boolean
    readyDate: datetime
    archived: boolean
    blocked: boolean
    comment: text
  relations:
    lane:
      class: tkLane
      local: lane_id
      foreign: id
      type: one
    creator:
      class: sfGuardUser
      local: creator_id
      foreign: id
      type: one
    area:
      class: tkArea
      local: area_id
      foreign: id
      type: one
    user:
      class: sfGuardUser
      local: sf_guard_user_id
      foreign: id
      type: one
    root:
      class: tkTask
      local: root_id
      foreign: id
      type: one